/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package puntomedio.gui;

import javax.swing.JOptionPane;
import puntomedio.PuntoMedioCirculos;
import puntomedio.PuntoMedioLineas;

/**
 *
 * @author edwin
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     * @param ventana
     */
    VentanaPanel ventanaLinea, ventanaCirculo;
    PuntoMedioLineas puntoMedioLinea;
    PuntoMedioCirculos puntoMediocirculos;
    public MainGUI() {
        ventanaLinea = new VentanaPanel();
        ventanaLinea.setBounds(10,10,801,601);
        ventanaCirculo = new VentanaPanel();
        ventanaCirculo.setBounds(10,10,801,601);        
        initComponents();
        this.panelCentralLinea.add(ventanaLinea);
        this.panelCentralCircu.add(ventanaCirculo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        controlesPanel = new javax.swing.JPanel();
        jLXIni = new javax.swing.JLabel();
        jTFXIni = new javax.swing.JTextField();
        jLYIni = new javax.swing.JLabel();
        jTFYIni = new javax.swing.JTextField();
        jBPintarLinea = new javax.swing.JButton();
        jLXFinal = new javax.swing.JLabel();
        jTFYFinal = new javax.swing.JTextField();
        jTFXFinal = new javax.swing.JTextField();
        jLYFinal = new javax.swing.JLabel();
        panelCentralLinea = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        controlesPanel1 = new javax.swing.JPanel();
        jLXCentro = new javax.swing.JLabel();
        jTFXCentro = new javax.swing.JTextField();
        jLYCentro = new javax.swing.JLabel();
        jTFYCentro = new javax.swing.JTextField();
        jBPintarCircu = new javax.swing.JButton();
        jLRadio = new javax.swing.JLabel();
        jTFRadio = new javax.swing.JTextField();
        panelCentralCircu = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Implementación Algoritmo del Punto Medio ( Breshenhan )");

        jLabel2.setText("Por:");

        jLabel3.setText("Edwin Gamboa (1310233) - Roger Fernandez (1310229) -  David Fernando Zuluaga (1310294)");

        controlesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Coordenadas Línea"));

        jLXIni.setText("X inicial:");

        jTFXIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFXIniActionPerformed(evt);
            }
        });

        jLYIni.setText("Y inicial:");

        jTFYIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFYIniActionPerformed(evt);
            }
        });

        jBPintarLinea.setText("Pintar");
        jBPintarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPintarLineaActionPerformed(evt);
            }
        });

        jLXFinal.setText("X final:");

        jTFYFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFYFinalActionPerformed(evt);
            }
        });

        jTFXFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFXFinalActionPerformed(evt);
            }
        });

        jLYFinal.setText("Y final:");

        javax.swing.GroupLayout controlesPanelLayout = new javax.swing.GroupLayout(controlesPanel);
        controlesPanel.setLayout(controlesPanelLayout);
        controlesPanelLayout.setHorizontalGroup(
            controlesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLXIni)
                .addGap(3, 3, 3)
                .addComponent(jTFXIni, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLYIni)
                .addGap(3, 3, 3)
                .addComponent(jTFYIni, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLXFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFXFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLYFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFYFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBPintarLinea)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        controlesPanelLayout.setVerticalGroup(
            controlesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLXIni)
                    .addComponent(jTFXIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLYIni)
                    .addComponent(jTFYIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLXFinal)
                    .addComponent(jTFXFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLYFinal)
                    .addComponent(jTFYFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPintarLinea))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCentralLinea.setPreferredSize(new java.awt.Dimension(810, 610));

        javax.swing.GroupLayout panelCentralLineaLayout = new javax.swing.GroupLayout(panelCentralLinea);
        panelCentralLinea.setLayout(panelCentralLineaLayout);
        panelCentralLineaLayout.setHorizontalGroup(
            panelCentralLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelCentralLineaLayout.setVerticalGroup(
            panelCentralLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCentralLinea, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
            .addComponent(controlesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(controlesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCentralLinea, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lineas", jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(810, 610));

        controlesPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Coordenadas Centro Circunferencia"));

        jLXCentro.setText("X:");

        jTFXCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFXCentroActionPerformed(evt);
            }
        });

        jLYCentro.setText("Y:");

        jTFYCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFYCentroActionPerformed(evt);
            }
        });

        jBPintarCircu.setText("Pintar");
        jBPintarCircu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPintarCircuActionPerformed(evt);
            }
        });

        jLRadio.setText("Radio:");

        jTFRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlesPanel1Layout = new javax.swing.GroupLayout(controlesPanel1);
        controlesPanel1.setLayout(controlesPanel1Layout);
        controlesPanel1Layout.setHorizontalGroup(
            controlesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlesPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLXCentro)
                .addGap(3, 3, 3)
                .addComponent(jTFXCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLYCentro)
                .addGap(3, 3, 3)
                .addComponent(jTFYCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLRadio)
                .addGap(2, 2, 2)
                .addComponent(jTFRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBPintarCircu)
                .addContainerGap(479, Short.MAX_VALUE))
        );
        controlesPanel1Layout.setVerticalGroup(
            controlesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlesPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLXCentro)
                    .addComponent(jTFXCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLYCentro)
                    .addComponent(jTFYCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPintarCircu)
                    .addComponent(jLRadio)
                    .addComponent(jTFRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCentralCircu.setPreferredSize(new java.awt.Dimension(810, 610));

        javax.swing.GroupLayout panelCentralCircuLayout = new javax.swing.GroupLayout(panelCentralCircu);
        panelCentralCircu.setLayout(panelCentralCircuLayout);
        panelCentralCircuLayout.setHorizontalGroup(
            panelCentralCircuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        panelCentralCircuLayout.setVerticalGroup(
            panelCentralCircuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(controlesPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelCentralCircu, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(controlesPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCentralCircu, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Circunferencias", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFXFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFXFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFXFinalActionPerformed

    private void jTFYFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFYFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFYFinalActionPerformed

    private void jBPintarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPintarLineaActionPerformed
        // TODO add your handling code here:
        try{            
            int x0 = Integer.parseInt(jTFXIni.getText());
            int y0 = Integer.parseInt(jTFYIni.getText());
            int x1 = Integer.parseInt(jTFXFinal.getText());
            int y1 = Integer.parseInt(jTFYFinal.getText());
            if(x0>=(ventanaLinea.X_CENTRO*-1) && x0<=ventanaLinea.X_CENTRO
                && y0>=(ventanaLinea.Y_CENTRO*-1) && y0<=ventanaLinea.Y_CENTRO
                && x1>=(ventanaLinea.X_CENTRO*-1) && x1<=ventanaLinea.X_CENTRO
                && y1>=(ventanaLinea.Y_CENTRO*-1) && y1<=ventanaLinea.Y_CENTRO){
                puntoMedioLinea = new PuntoMedioLineas(ventanaLinea);
                puntoMedioLinea.puntoMedio(x0, y0, x1, y1);
                ventanaLinea.repaint();
            }else{
                JOptionPane.showMessageDialog(this, "Recuerde que solo puede ingresar números: \n"
                    + "\tentre " + (ventanaLinea.X_CENTRO*-1) +" y " + ventanaLinea.X_CENTRO +" para X y \n"
                    + "\tentre "+ (ventanaLinea.Y_CENTRO*-1) +" y " + ventanaLinea.Y_CENTRO +" para Y.", null,
                    JOptionPane.ERROR_MESSAGE);
            }
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Recuerde que solo puede ingresar números enteros.", null,
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBPintarLineaActionPerformed

    private void jTFYIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFYIniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFYIniActionPerformed

    private void jTFXIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFXIniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFXIniActionPerformed

    private void jTFXCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFXCentroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFXCentroActionPerformed

    private void jTFYCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFYCentroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFYCentroActionPerformed

    private void jBPintarCircuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPintarCircuActionPerformed
        // TODO add your handling code here:
        try{            
            int xCentroCirc = Integer.parseInt(jTFXCentro.getText());
            int yCentroCirc = Integer.parseInt(jTFYCentro.getText());
            int radio = Integer.parseInt(jTFRadio.getText());
            if(xCentroCirc>=(ventanaCirculo.X_CENTRO*-1) 
                    && xCentroCirc<=ventanaCirculo.X_CENTRO
                && yCentroCirc>=(ventanaCirculo.Y_CENTRO*-1) 
                    && yCentroCirc<=ventanaCirculo.Y_CENTRO
                    && radio >= 0 && radio <= ventanaCirculo.X_CENTRO){
                puntoMediocirculos = new PuntoMedioCirculos(ventanaCirculo, xCentroCirc, yCentroCirc);
                puntoMediocirculos.puntoMedioCirculos(radio);
                ventanaCirculo.repaint();
            }else{
                JOptionPane.showMessageDialog(this, "Recuerde que solo puede ingresar números: \n"
                    + "\tentre " + (ventanaCirculo.X_CENTRO*-1) +" y " + ventanaCirculo.X_CENTRO +" para X y \n"
                    + "\tentre "+ (ventanaCirculo.Y_CENTRO*-1) +" y " + ventanaCirculo.Y_CENTRO +" para Y.", null,
                    JOptionPane.ERROR_MESSAGE);
            }
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Recuerde que solo puede ingresar números enteros.", null,
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBPintarCircuActionPerformed

    private void jTFRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFRadioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlesPanel;
    private javax.swing.JPanel controlesPanel1;
    private javax.swing.JButton jBPintarCircu;
    private javax.swing.JButton jBPintarLinea;
    private javax.swing.JLabel jLRadio;
    private javax.swing.JLabel jLXCentro;
    private javax.swing.JLabel jLXFinal;
    private javax.swing.JLabel jLXIni;
    private javax.swing.JLabel jLYCentro;
    private javax.swing.JLabel jLYFinal;
    private javax.swing.JLabel jLYIni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTFRadio;
    private javax.swing.JTextField jTFXCentro;
    private javax.swing.JTextField jTFXFinal;
    private javax.swing.JTextField jTFXIni;
    private javax.swing.JTextField jTFYCentro;
    private javax.swing.JTextField jTFYFinal;
    private javax.swing.JTextField jTFYIni;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelCentralCircu;
    private javax.swing.JPanel panelCentralLinea;
    // End of variables declaration//GEN-END:variables
}
